AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Real-time communication using API Gateway WebSocket and Lambda

Resources:
  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: MyWebSocketApi
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $connect
      AuthorizationType: NONE
      OperationName: ConnectRoute
      Target: !Join
        - /
        - - integrations
          - !Ref ConnectIntegration

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: DisconnectRoute
      Target: !Join
        - /
        - - integrations
          - !Ref DisconnectIntegration

  WebSocketIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt ConnectDisconnectFunction.Arn

  ConnectDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.umaxcode.ConnectDisconnectLambdaHandler::handleRequest
      Runtime: java21
      MemorySize: 512
      Timeout: 30
      CodeUri: .
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - execute-api:ManageConnections
              Resource: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*"

  WebSocketConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: WebSocketConnections
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: emailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  WebSocketDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    Properties:
      ApiId: !Ref WebSocketApi
      Description: WebSocket API Deployment

  WebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: test
      ApiId: !Ref WebSocketApi
      DeploymentId: !Ref WebSocketDeployment
      AutoDeploy: true

Outputs:
  WebSocketApiUrl:
    Description: "WebSocket API URL"
    Value: !Join
      - ""
      - - "wss://"
        - !Ref WebSocketApi
        - ".execute-api."
        - !Ref "AWS::Region"
        - ".amazonaws.com/"
        - !Ref WebSocketStage